/* COPYRIGHT (C) HARRY CLARK 2024 */

/* SEGA MEGA DRIVE EMULATOR */

/* THIS FILE PERTAINS TO THE MAIN FUNCTIONS OF THE CPU */

#include "68000.h"

#undef USE_CPU

#if defined(M68K_CPU_ARGS)
#define	M68K_CPU_ARGS
#else
#define M68K_CPU_ARGS

#define		M68K_CALLBACK_RESET			1
#define		M68K_CALLBACK_FUNC			2

#endif

/* DISCERN THE RUDIMENTARY AMOUNT OF CPU CYCLES */
/* THE CPU WILL GOVERN OVER THE COURSE OF IT'S RUN TIME */

/* THIS WILL ENCOMPASS THE WIDE BITWISE VARIETY */
/* THROUGH THE CONCISE MEANS OF EVALUATING THE SIZE OF */
/* OF THE DESIGNATED MEMORY */

/* SEE 1.1 USER PROGRAMMING MODEL https://www.nxp.com/docs/en/reference-manual/M68000PRM.pdf#page=13 */

void INITIALISE_68K_CYCLES(char* CPU_68K_CYCLES)
{
	CPU_68K_CYCLES = malloc(sizeof(CPU_68K_CYCLES));

	/* THIS LOOP WILL CHECK FOR EVERY SUBSEQUENT BITWISE */
	/* OPERATION AND EVALUATE IT'S DESIGNATED MEMORY */

	/* THE FIRST CO-EFFICIENT REPRESENTS THE BITWISE LENGTH OF THE OPERATION */
	/* THE SECOND CO-EFFICIENT REPRESENTS THE SIZE OF THE REGISTER */

	for (size_t INDEX = 0; INDEX < sizeof(CPU_68K_CYCLES); INDEX++)
	{
		switch (INDEX / 16)
		{
		case 0:
			CPU_68K_CYCLES[INDEX] = 8*7;
			break;

		case 1:
			CPU_68K_CYCLES[INDEX] = 16*7;
			break;

		case 2:
			CPU_68K_CYCLES[INDEX] = 24*7;

		default:
			CPU_68K_CYCLES[INDEX] = 32*7;
			break;
		}
	}
}

/* ACCESS EACH RESPECTIVE REGISTER FROM THE ENUMERATION */
/* RETURN THE CORRESPONDENCE IN RELATION TO THE SIZE */

/* FOR EASE OF USE WHEN ACCESSING METHODS, I HAVE CREATED A MACRO */
/* TO BE ABLE TO RETURN THE CORRESPONDING ADDRESS VALUE IN RELATION */
/* TO THE INDEXXING OF THE REGISTER ARRAY */

U32 CPU_ACCESS_REGISTERS(CPU_68K_REGS REGISTER, unsigned VALUE)
{
	struct CPU_68K* CPU_68K;

	/* IF THERE IS NO ACCESSIBLE METHODS */
	/* WE SPECIFICALLY ALLOCATE MEMORY SAID ACCESSING OF REGISTERS */

	CPU_68K = malloc(sizeof(struct CPU_68K));

	switch(REGISTER)
	{
		case M68K_REG_D0: CPU_68K->REGISTER_BASE[0] = (U32*)M68K_RETURN_ADDRESS(VALUE); return CPU_68K->REGISTER_BASE[0];
		case M68K_REG_D1: CPU_68K->REGISTER_BASE[1] = (U32*)M68K_RETURN_ADDRESS(VALUE); return CPU_68K->REGISTER_BASE[1];
		case M68K_REG_D2: CPU_68K->REGISTER_BASE[2] = (U32*)M68K_RETURN_ADDRESS(VALUE); return CPU_68K->REGISTER_BASE[2];
		case M68K_REG_D3: CPU_68K->REGISTER_BASE[3] = (U32*)M68K_RETURN_ADDRESS(VALUE); return CPU_68K->REGISTER_BASE[3];
		case M68K_REG_D4: CPU_68K->REGISTER_BASE[4] = (U32*)M68K_RETURN_ADDRESS(VALUE); return CPU_68K->REGISTER_BASE[4];
		case M68K_REG_D5: CPU_68K->REGISTER_BASE[5] = (U32*)M68K_RETURN_ADDRESS(VALUE); return CPU_68K->REGISTER_BASE[5];
		case M68K_REG_D6: CPU_68K->REGISTER_BASE[6] = (U32*)M68K_RETURN_ADDRESS(VALUE); return CPU_68K->REGISTER_BASE[6];
		case M68K_REG_D7: CPU_68K->REGISTER_BASE[7] = (U32*)M68K_RETURN_ADDRESS(VALUE); return CPU_68K->REGISTER_BASE[7];
		
		case M68K_REG_A0: CPU_68K->REGISTER_BASE[8] = (U32*)M68K_RETURN_ADDRESS(VALUE); return CPU_68K->REGISTER_BASE[8];
		case M68K_REG_A1: CPU_68K->REGISTER_BASE[9] = (U32*)M68K_RETURN_ADDRESS(VALUE); return CPU_68K->REGISTER_BASE[9];
		case M68K_REG_A2: CPU_68K->REGISTER_BASE[10] = (U32*)M68K_RETURN_ADDRESS(VALUE); return CPU_68K->REGISTER_BASE[10];
		case M68K_REG_A3: CPU_68K->REGISTER_BASE[11] = (U32*)M68K_RETURN_ADDRESS(VALUE); return CPU_68K->REGISTER_BASE[11];
		case M68K_REG_A4: CPU_68K->REGISTER_BASE[12] = (U32*)M68K_RETURN_ADDRESS(VALUE); return CPU_68K->REGISTER_BASE[12];
		case M68K_REG_A5: CPU_68K->REGISTER_BASE[13] = (U32*)M68K_RETURN_ADDRESS(VALUE); return CPU_68K->REGISTER_BASE[13];
		case M68K_REG_A6: CPU_68K->REGISTER_BASE[14] = (U32*)M68K_RETURN_ADDRESS(VALUE); return CPU_68K->REGISTER_BASE[14];
		case M68K_REG_A7: CPU_68K->REGISTER_BASE[15] = (U32*)M68K_RETURN_ADDRESS(VALUE); return CPU_68K->REGISTER_BASE[15];

		case M68K_REG_PC: return (U32*)M68K_RETURN_ADDRESS(CPU_68K->PC);

		case M68K_REG_USP:
			if(FLAG_S) CPU_68K->REGISTER_BASE[15] = (U32*)M68K_RETURN_ADDRESS(VALUE);
			return;

		case M68K_REG_ISP:
			if(FLAG_S) CPU_68K->REGISTER_BASE[14] = (U32*)M68K_RETURN_ADDRESS(VALUE);
			return;

		case M68K_REG_SP:
			return CPU_68K->DATA_REGISTER[15];

		case M68K_REG_SFC:
			return CPU_68K->SOURCE_FUNCTION_COUNTER;

		case M68K_REG_DFC:
			return CPU_68K->DEST_FUNCTION_COUNTER;

		case M68K_REG_VBR:
			return CPU_68K->VBR;

		case M68K_REG_CACR:
			return CPU_68K->CACHE_CONTROL;

		case M68K_REG_CAAR:
			return CPU_68K->CACHE_ADDRESS;

		case M68K_REG_IR:
			return CPU_68K->INDEX_REGISTER;

		default: 
			return M68K_RETURN_ADDRESS(VALUE);	
	}
}

/* INTIALISE THE INTEGER TYPE CALLBACK */
/* THIS CALLBACK REFERS TO THE WAY IN WHICH THE DESIGNATED TYPE */
/* IS ABLE TO COMMUNICATE BETWEEN ALL AREAS OF EACH RESPECTIVE REGISTER */

/* SEE: https://www.nxp.com/docs/en/reference-manual/M68000PRM.pdf#page=14 */

/* ALLOCATE A DESIGNATED CHUNK OF MEMORY ASSUMING THE NOTION */
/* THAT THE RESPECTIVE REGISTER NEEDS TO ACCESS VALUES OF THIS ASSOCIATION */

#undef M68K_CPU_ARGS

void M68K_SET_INT_CALLBACK(int* CALLBACK, int* LEVEL)
{
	M68K_CALLBACK_INT(CALLBACK ? CALLBACK : (int*)sizeof(*LEVEL), 0);
}

/* FOLLOWING ON FROM THE SAME PRINCIPLES AS ABOVE */
/* INITIALISE THE REMAINING CALLBACKS */

void M68K_SET_FUNC_CALLBACK(int* CALLBACK, int* LEVEL)
{
	M68K_FUNC_CALLBACK(CALLBACK ? CALLBACK : (int*)sizeof(*LEVEL), 0);
}

/* DETERMINE THE STEP LATENCY OF RELEVANT MOVE BASED INSTRUCTIONS */
/* THIS CHECKS THE MASK TO PROCESS SAID IRQ */

void M68K_SET_MOVE_IRQ_INT()
{
	struct CPU_68K* CPU_68K;

	/* FIRSTLY, WE BEGIN TO EVALUATE THE SIZE OF THE CURRENTLY EXECUTED INSTRUCTION */
	/* THIS IS SO THAT WHEN CHECKING THE MASK, WE DON'T RUN INTO BUFFER OVERFLOWS */

	assert(CPU_68K->PC <= ADDRESS_WIDTH_32);
	assert(CPU_68K->MEMORY_ADDRESS[7] % 2 == 0);

	/* SECONDLY, EVALUATE WHICH INSTRUCTION IS BEING EXECUTED */
	/* CREATE A CAST TO EVALUATE THE SIZE OF THE RELEVANT INSTRUCTION */

	CPU_68K->INSTRUCTION_REGISTER = (U16*)malloc(M68K_FETCH_INSTR(&CPU_68K));

	/* THIRDLY, EVALUATE THE STEP LATENCY TO DETERMINE THE EXECUTION TIME */	
	/* THIS IS BY ASSUMING THAT THE CORRESPONDING INSTRUCTION HAS A RELATIVE SIZE */

	/* FROM THERE, DETERMINE IF THE INSTRUCTION CAN BE OR IS HOUSED IN THE INDEX REGISTER */
	/* IF NOT, MAKE ROOM FOR THE CURRENT INDEX */

	int IRQ_LATENCY;
	int INT_LEVEL;

	if(!IRQ_LATENCY && M68K_REG_IR & 0xF000 != 0x2000) 
	{
		M68K_CYCLE_CLOCK_SHIFT(CPU_68K->INSTRUCTION_CYCLES[M68K_REG_IR]);
	}

	INT_LEVEL <= 8;
}

void M68K_RUN(void)
{
	struct CPU_68K* CPU_68K;
	int CYCLES;

	/* WHILE WORKING, CHECK IF THE INSTRUCTION CYCLES */
	/* MATCHES THE CORRESPONDNECE IN THE CYCLE CACHE */

	if(CPU_68K->INSTRUCTION_CYCLES >= CYCLES)
	{
		return;
	}

	/* EXECUTE RELEVANT INSTRUCTION */

	CPU_68K->INSTRUCTION_REGISTER[M68K_REG_IR];
	M68K_CYCLE_CLOCK_SHIFT(CPU_68K->INSTRUCTION_CYCLES[M68K_REG_IR]);

}

/* BASED ON THE FUNCTIONALITY ABOVE, WE CAN BEGIN TO EVALUATE WHICH INSTRUCTIONS ARE BEING FETCHED */
/* THIS IS BASED ON THEIR PRIORITY LEVEL IN RELATION TO WHICH INSTRUCTION IS BEING FETCHED FROM THE PC */

U16* M68K_FETCH_INSTR(struct CPU_68K* CPU_68K)
{
	unsigned WORD;

	/* IF THE PROGRAM COUNTER HAS JUMPED TO ANOTHER SUBROUTINE */
	/* OR INSTRUCTION, SHIFT LOGICAL TO THE NEXT PROBABLE INSTRUCTION */

	if(CPU_68K->PC != CPU_68K->PREVIOUS_ADDRESS)
	{
		WORD = M68K_READ_16(CPU_68K->MEMORY_ADDRESS, CPU_68K->MEMORY_DATA);
		CPU_68K->PC = CPU_68K->PREVIOUS_ADDRESS, sizeof(CPU_68K->PC + 2);
	}

	return WORD;
}
