/* Copyright(C) 2023 Harry Clark * /

/* SEGA Mega Drive Emulator */

/* THIS FILE PERTAINS TO THE FUNCTIONALITY OF THE INSTRUCTION SET IN ACCORDANCE */
/* WITH THE INSTRUCTIONS PERTAINING TO THE ARCHITECTURE OF THE CPU */

/* NESTED INCLUDES */

#include "instruction.h"

#ifdef USE_ISA

/* IN CONJUNCTION WITH USING THE DIRECTIVE IN THE HEADER FILE */
/* THIS IS TO CREATE STATICALLY AVAILABLE OBJECTS FOR EACH AND */
/* EVERY ASSEMBLER INSTRUCTION PART OF THE M68K */

INSTRUCTION_FUNCTION(ADD);
INSTRUCTION_FUNCTION(ADD_DECIMAL_EXTEND);
INSTRUCTION_FUNCTION(ADD_ADDRESS);
INSTRUCTION_FUNCTION(ADD_IMMEDIATE);
INSTRUCTION_FUNCTION(ADD_QUICK);
INSTRUCTION_FUNCTION(ADD_EXTENDED);

INSTRUCTION_FUNCTION(AND_LOGICAL);
INSTRUCTION_FUNCTION(AND_IMMEDIATE);
INSTRUCTION_FUNCTION(AND_IMMEDIATE_CONDITION);
INSTRUCTION_FUNCTION(AND_IMMEDIATE_STATUS_REG);

INSTRUCTION_FUNCTION(ARITHMETIC_SHIFT_LEFT);
INSTRUCTION_FUNCTION(ARITHMETIC_SHIFT_RIGHT);


INSTRUCTION_FUNCTION(BIT_CHANGE);
INSTRUCTION_FUNCTION(BIT_CLEAR);
INSTRUCTION_FUNCTION(BIT_FIELD);
INSTRUCTION_FUNCTION(BIT_FIELD_SET);
INSTRUCTION_FUNCTION(BIT_FIELD_CHANGE);
INSTRUCTION_FUNCTION(BIT_FIELD_CLEAR);
INSTRUCTION_FUNCTION(BIT_FIELD_SIGNED);
INSTRUCTION_FUNCTION(BIT_FIELD_UNSIGNED);
INSTRUCTION_FUNCTION(BIT_FIRST_ONE);
INSTRUCTION_FUNCTION(BIT_TEST);

#endif