;; COPYRIGHT (C) HARRY CLARK 2024

;; SEGA MEGA DRIVE EMULATOR

;; THIS FILE PERTAINS TOWARDS THE CONJUNCTIVE FUNCTIONALITY ;;
;; BETWEEN THE 68000 AND Z80 - PERTAINING TOWARDS OPCODES ;;
;; THAT ARE USED TO DETERMINE INSTRUCTION AND EXECUTION METHODS ;;

INCLUDE "macros.asm"

;; READ THE CACHE OF THE CONDITION CODE REGISTER
;; DETERMINE WHICH FLAGS ARE BEING USED AT A GIVEN INSTRUCTION
;; GIVEN THE CACHE, THIS WILL DETERMINE THE DATA BEING PASSED THROUGH
;; IN RELATION TO THE FLAGS

CACHE_CCR:    
    MOVE AL,[__SR]          ;; LOGICAL OR FROM CCR TO AL
    MOVE AH                 ;; SHIFT INTO AH
    AND AX, 0xC10           ;; ISOLATE EXTEND FLAG BEFORE STORING THE CONDITION
    SHR AL, 4               ;; SHIFT EXTEND FLAG INTO BIT 4
    MOVE [__X], AL          ;; STORE THE CONTENTS OF SAID FLAG
    MOVE AL,[__SR]          ;; READ CURRENT LOGICAL OR SHIFT
    RTS

;; COUROUTINE FOR DECODING RELATIVE EXTENSIONS 
;; WITH A WORD-WISE LENGTH IN EDX

DECODE_EXT:
    align 16                ;; SET SIGNED ALIGNMENT FOR LENGTH
    PUSH ECX                ;; PUSH THE ALIGNMENT INTO COUNTER
    RTS
    
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;;                          END OF FILE
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;