#include "mapper.h"

M68K_MAPPER::M68K_MAPPER(uint32_t MAP_SUPERVISOR_FUNCTION, uint32_t MAP_DATA_FUNCTION)
{
	this->pSFC = MAP_SUPERVISOR_FUNCTION;
	this->pDFC = MAP_DATA_FUNCTION;
}

M68K_MAPPER::~M68K_MAPPER()
{

}