/* Copyright(C) 2023 Harry Clark * /

/* SEGA Mega Drive Emulator */

/* THIS FILE PERTAINS TOWARDS THE FUNCTIONALITY OF THE PSG */
/* THE PSG GOVERNS THE ARRANGEMENT OF SOUND EFFECTS IN CONJUNCTION */
/* WITH THE FUNCTIONALITY OF THE YM2612 TO COMPOSE SOUNDS AND MUSIC */

/* NESTED INCLUDES */

#include "psg.h"

#undef USE_PSG

/* INITIALISE THE CONSTANT STRUCTURE OF THE PSG */
/* THIS IS DONE BY ASSEMBLING AN ARBITARY LOOKUP TABLE SUCH THAT */
/* I AM ABLE TO EFFICIENTLY SORT BETWEEN EACH VOLUME LEVEL BASED ON */
/* THEIR RESPECTIVE CHANNEL */

STATIC
void PSG_CONST_INIT(PSG_BASE* PSG_BASE)
{
    /* CREATE AN ARBITARY VOLUME TABLE */
    /* WITH 16 VALUES INDICATING THE FM CHANNELS */
    /* AND OTHER INSTANCES */

    S16* VOLUME_TABLE[16];

    /* EVALUATE THE SIZE OF THE PSG VOLUME TABLE */
    /* BASED ON THE RELATIVE SIZE OF THE REGISTER */

    for (S16 i = 0; i < PSG_LOOKUP_LENGTH; i++)
    {
        VOLUME_TABLE[i] = sizeof(PSG_CHANNEL_VOLUME);
        PSG_BASE->VOLUME[i][0] += sizeof(VOLUME_TABLE[i]);      // POSTIVE PHASE
        PSG_BASE->VOLUME[i][1] -= sizeof(VOLUME_TABLE[i]);      // NEGATIVE PHASE
    }

    PSG_BASE->VOLUME[0xF][0] = 0;
    PSG_BASE->VOLUME[0xF][1] = 0;
}