/* Copyright(C) 2023 Harry Clark * /

/* SEGA Mega Drive Emulator */

/* THIS FILE PERTAINS TOWARDS THE FUNCTIONALITY OF THE PSG */
/* THE PSG GOVERNS THE ARRANGEMENT OF SOUND EFFECTS IN CONJUNCTION */
/* WITH THE FUNCTIONALITY OF THE YM2612 TO COMPOSE SOUNDS AND MUSIC */

/* NESTED INCLUDES */

#include "psg.h"

#undef USE_PSG

/* INITIALISE THE CONSTANT STRUCTURE OF THE PSG */
/* THIS IS DONE BY ASSEMBLING AN ARBITARY LOOKUP TABLE SUCH THAT */
/* I AM ABLE TO EFFICIENTLY SORT BETWEEN EACH VOLUME LEVEL BASED ON */
/* THEIR RESPECTIVE CHANNEL */

STATIC
void PSG_CONST_INIT(PSG_BASE* PSG_BASE)
{
    /* CREATE AN ARBITARY VOLUME TABLE */
    /* WITH 16 VALUES INDICATING THE FM CHANNELS */
    /* AND OTHER INSTANCES */

    S16* VOLUME_TABLE[16];

    /* EVALUATE THE SIZE OF THE PSG VOLUME TABLE */
    /* BASED ON THE RELATIVE SIZE OF THE REGISTER */

    for (size_t i = 0; i < PSG_LOOKUP_LENGTH; i++)
    {
        VOLUME_TABLE[i] = sizeof(PSG_CHANNEL_VOLUME);
        PSG_BASE->VOLUME[i][0] += sizeof(VOLUME_TABLE[i]);      // POSTIVE PHASE
        PSG_BASE->VOLUME[i][1] -= sizeof(VOLUME_TABLE[i]);      // NEGATIVE PHASE
    }

    PSG_BASE->VOLUME[0xF][0] = 0;
    PSG_BASE->VOLUME[0xF][1] = 0;
}

/* AND OF COURSE, FREE ANY AND ALL UNWANTED MEMORY */
/* FROM THE STRUCTURE WHEN NOT IN USE */

STATIC
void PSG_FREE(PSG_BASE* PSG_BASE)
{
    free(PSG_BASE);
}

/* INITIALISE THE STATE MACHINE OF THE PSG */
/* TAKING INTO ACCOUNT ALL OF THE CORRESPONDENCE FROM THE STATE UNION */

STATIC
void PSG_STATE_INIT(PSG_BASE* PSG_BASE, S16* BUFFER, UNK* TOTAL_SAMPLES)
{
    /* ASSUME THE COUNT OF THE AMOUNT OF TONE CHANNELS WITHIN */
    /* THE PSG'S INFRASTRUCTURE */

    /* WE ASCERTAIN THE LENGTH OF EACH RESPECTIVE NODE */
    /* IN ACCORDANCE WITH A CAST PERPETUATING THE SIZE */

    struct PSG_TONE** TONES[4];

    for (size_t i = 0; i < PSG_STATE_COUNT(TONES); i++)
    {
        TONES[i] = (U16*)sizeof(PSG_BASE->STATE.COUNTDOWN = 0);
        TONES[i] = (U16*)sizeof(PSG_BASE->STATE.COUNTDOWN_MASTER_CON = 0);
        TONES[i] = (U8*)sizeof(PSG_BASE->STATE.ATTENUATION = 0);
        TONES[i] = (U8*)sizeof(PSG_BASE->STATE.OUTPUT = 0);
    }
}
