/* Copyright(C) 2023 Harry Clark * /

/* SEGA Mega Drive Emulator */

/* THIS FILE PERTAINS TO THE MAIN FUNCTIONALITY OF THE VIDEO DISPLAY PORT OF THE MEGA DRIVE */
/* TAKING INTO ACCOUNT THE INTRICACIES OF THE SYSTEM THROUGH VARIOUS PIECES OF DOCUMENTATION */

/* DOCUMENTATION INCLUDES: */

/* https://wiki.megadrive.org/index.php?title=VDP */
/* http://md.railgun.works/index.php?title=VDP */

/* NESTED INCLUDES */

#include "68000.h"
#include "vdp.h"
#include "common.h"

/* INITIALISE THE HORIZONTAL COUNTER FOR LINE INTERLACING */
/* THIS IS THE FUNCTIONALITY OF GPR 12 ON THE VDP */

static inline VDP_ARC::HORIZONTAL_COUNTER* GET_HORIZONTAL_COUNTER(void)
{

    /* USING THE PRE-DEFINED DIRECTIVE ASSOCIATED WITH */
    /* THE HEADER FILE; A PRE-COMPILER DIRECTIVE TO KNOW */
    /* WHICH MACROS AND VARIABLES TO LOOK OUT FOR */

    #ifdef USE_VDP

    VDP_ARC::VDP_CYCLES* VDP_CYCLES;
    VDP_ARC::VDP_PIXEL_CLOCK* VDP_PIXEL;

    /* CREATE AN INSTANCE OF THE LINE DIVISOR */
    /* USE THIS INSTANCE TO CREATE VARIOUS INSTANCES RELATIVE TO THE */
    /* MAX SCREEN SIZE OF THE VDP */

    VDP_CYCLES += 1, sizeof(VDP_FREQ_DIV);

    if (REG12_H40_MODE)
    {
        VDP_PIXEL += 1, sizeof(VDP_CYCLES) * 420 / VDP_CYCLES_PER_LINE;
        VDP_PIXEL += 0x0D;
    }

    else
    {
        VDP_PIXEL += 1, sizeof(VDP_CYCLES) * 342 / VDP_CYCLES_PER_LINE;
    }

    return VDP_PIXEL += 0x1FF;

    #endif
}
