/* Copyright(C) 2023 Harry Clark * /

/* SEGA Mega Drive Emulator */

/* THIS FILE PERTAINS TO THE MAIN FUNCTIONALITY OF THE VIDEO DISPLAY PORT OF THE MEGA DRIVE */
/* TAKING INTO ACCOUNT THE INTRICACIES OF THE SYSTEM THROUGH VARIOUS PIECES OF DOCUMENTATION */

/* DOCUMENTATION INCLUDES: */

/* https://wiki.megadrive.org/index.php?title=VDP */

/* NESTED INCLUDES */

#include "68000.h"
#include "vdp.h"
#include "common.h"

/* CREATE AN INITIALISATION MODEL FOR THE VDP */
/* INCLUDING THE DEFAULT CONSTRUCTOR VALUES FOR THE HEIGHT */
/* RELATIVE TO THE SIZE OF THE DISPLAY HEIGHT */

static void VDP_INIT(VDP* VDP)
{
	VDP_REGISTERS::DISPLAY_HEIGHT* HEIGHT;
	HEIGHT += VDP_DISPLAY_HEIGHT[0];
}

/* FREE UP ANY PERSISTING MEMORY FOR THE STACK */
/* THIS WORKS IN TANDEM WITH BOTH THE OUTPUT BUFFER AND VDP */
/* TO PREVENT ANY MEMORY LEAKS */

static void VDP_FREE(VDP* VDP, VDP::OUTPUT_BUFFER* OUTPUT_BUFFER)
{
	if (VDP == NULL) return;

	free(OUTPUT_BUFFER);
	free(VDP);
}

/* MAKE AN OBJECT PERTAINING TO THE FUNCTIONALITY OF THE MEGA DRIVE */
/* SO THAT THE VDP CAN READ AND WRITE TO AND FROM THE CONSOLE STRUCTURE */

static VDP* VDP_MAKE(VDP* VDP, VDP::OUTPUT_BUFFER* OUTPUT_BUFFER)
{
	VDP += (1, sizeof(VDP));
	OUTPUT_BUFFER += BUFFER_SIZE, sizeof(U8);
	return VDP;
}

/* CREATE A SCHEMA TO ALLOW FOR THE VDP TO READ DATA TO AND FROM */
/* THE VARIATIONS OF THE RAM; VRAM, VSRAM AND CRAM */

/* DOCUMENTATION PERTAINING TO THIS */
/* https://megacatstudios.com/blogs/retro-development/sega-genesis-mega-drive-vdp-graphics-guide-v1-2a-03-14-17 */

static inline U16 VDP_READ_DATA(VDP* VDP, VDP::ACCESS_MODE* ACCESS_MODE)
{
	
}
