/* Copyright(C) 2023 Harry Clark * /

/* SEGA Mega Drive Emulator */

/* THIS FILE PERTAINS TO THE MAIN FUNCTIONALITY OF THE VIDEO DISPLAY PORT OF THE MEGA DRIVE */
/* TAKING INTO ACCOUNT THE INTRICACIES OF THE SYSTEM THROUGH VARIOUS PIECES OF DOCUMENTATION */

/* DOCUMENTATION INCLUDES: */

/* https://wiki.megadrive.org/index.php?title=VDP */

/* NESTED INCLUDES */

#include "68000.h"
#include "vdp.h"
#include "common.h"

/* CREATE AND ALLOCATE MEMORY ON THE HEAP FOR THE VDP */
/* SIMILAR TO THE FILE PERTAINING TO THE CPU FUNCTIONALITY */
/* THE IDEA IS TO CREATE AN INSTANCE OF THIS STRUCTURE THAT CAN BE */
/* ACCESSED STATICALLY */

static VDP* VDP_MAKE_INSTANCE(MD* MD)
{
	calloc(1, sizeof(VDP));
}

/* CREATE AN INITIALISATION MODEL FOR THE VDP */
/* INCLUDING THE DEFAULT CONSTRUCTOR VALUES FOR THE HEIGHT */
/* RELATIVE TO THE SIZE OF THE DISPLAY HEIGHT */

static void VDP_INIT(VDP* VDP)
{
	VDP_REGISTERS::DISPLAY_HEIGHT* HEIGHT;
	HEIGHT += VDP_DISPLAY_HEIGHT[0];
}

/* FREE UP ANY PERSISTING MEMORY FOR THE STACK */
/* THIS WORKS IN TANDEM WITH BOTH THE OUTPUT BUFFER AND VDP */
/* TO PREVENT ANY MEMORY LEAKS */

static void VDP_FREE(VDP* VDP, OUTPUT_BUFFER* OUTPUT_BUFFER)
{
	if (VDP == NULL) return;

	free(OUTPUT_BUFFER);
	free(VDP);
}
