/* COPYRIGHT (C) HARRY CLARK 2024 */

/* SEGA MEGA DRIVE EMULATOR */

/* THIS FILE PERTAINS TOWARDS THE FUNCTIONALITY SURROUDNING THE LOADING AND READING OF THE CARTRIDGE */

/* NESTED INCLUDES */

#include "cartridge.h"

#ifdef LOAD_MD_ROM

/* RETURN THE VALUE OF THE DESIGNATED CHECKSUM FROM THE PROVIDED ROM FILE */
/* A PRINT UTILITY WILL BE PROVIDED TO DEBUG THIS UTILIY */

U16 GET_CHECKSUM(U8* ROM, unsigned LENGTH, char* FILENAME)
{
    unsigned INDEX = 0;
    unsigned CHECKSUM = 0;

    for (INDEX = 0; INDEX < LENGTH; INDEX += 2)
    {
        CHECKSUM += ((ROM[INDEX] << 8) + ROM[INDEX + 1]); 
    }

    printf("Checksum for ROM: %s, 0x%x\n", FILENAME, CHECKSUM);
    return CHECKSUM;
}

/* PASS A RAW POINTER THROUGH THE HEADER OF THE ROM */
/* FROM THERE, PARSE ANY AND ALL SUBSEQUENT INFORMATION THAT PERTAINS */
/* TOWARDS THE STRUCTURE */

void MD_GET_ROM_INFO(char* HEADER)
{
    struct ROM_INFO* ROM = malloc(sizeof(struct ROM_INFO));

    int INDEX = 0;
    int ITERATOR = 0;
    unsigned char SYSTEM_TYPE = 0;

    /* THROUGH EVERY SUBSEQUENT READ OF THE ROM HEADER */
    /* CLEAR THE READER BUFFER, THAT WAY MISMATCHED DATA DOESN'T GET TRANSCODED */
    /* WHEN OTHER ROMS ARE LOADED */

    memset(ROM, 0, sizeof(struct ROM_INFO));

    if(SYSTEM_TYPE == SYSTEM_MD)
    {
        /* EVALUATE THE PRE-REQUISITES FROM THE ENTRY POINT */

        MD_DEFINE_INFO(&ROM_CONSOLE_TYPE, HEADER, 256, 16);
    } 

    free(ROM);
}

#endif